### ISSUE TITLE
SimpleWebRTC example is  not working anymore.

### ISSUE THREAD

**Issue by ghost** [xirdev/xsdk#1]
Hi , 

Yesterday the SimpleWebrtc example was working  just fine,   by some reason, today, it stoped to work, i don't know why,  i'm using the "secure : false"  method to connect with my credentials (the same config that i was using yesterday when everything was working).

Currently when i try to create the room, nothing happens, i can see the ice and the common requests   on the web inspector, but the room is never created, and i'm not getting any errors :(

Some ideas?

**Comment by ibraheemsadiq** [comment]
send me xirsys configuration file... are you using legacy system?!!

**Comment by ghost** [comment]
Hi, don't think so ,  i created my account,  aprox. 7 days ago.

My test credentials. (working this Friday at 23:55 without problems.)

``` javascript
  var xirsysConnect = {
    secure : false,
    data : {
        domain: 'zbox-developer-challenge.cl',
        application: 'zbox-developer-challenge',
        room : 'default',
        ident   : 'gbahamondez',
        secret: 'd6bb2e92-5a8e-11e5-8d2e-589d128ec481',
    }
};
```

I think there's something wrong with the signaling servers, for some reason they never respond, take a look.

<img width="1280" alt="screen shot 2015-09-14 at 8 21 40 am" src="https://cloud.githubusercontent.com/assets/3533121/9848682/bac40a9e-5ab9-11e5-903d-f64deb926043.png">

<img width="1280" alt="screen shot 2015-09-14 at 8 21 50 am" src="https://cloud.githubusercontent.com/assets/3533121/9848687/c1779afe-5ab9-11e5-87a9-97c45fde5c4d.png">

**Comment by richardblakely** [comment]
Hi Gonzalo, are you still experiencing the issue? Also, I recommend you reset your secret key since your old key is now public. Let us know if we can help.

**Comment by ghost** [comment]
Hi, @richardblakely  yes i'm experimenting  the issue   yet, and  ok, i changed the key thanks.

**Comment by Lazarus404** [comment]
Hi Gonzalo, I'm going to run the demo using your credentials a little later and will see if I can find what the fault is. In the meantime, can you try using a secure connection and by using the default application and see if either of those helps?

**Comment by ghost** [comment]
@Lazarus404 Hi,  i will try, the weird thing is this was working 100% this Friday, without any problems, with the same credentials, now looks like  something changed in the signaling server  because i never get  the response.

Thanks,

**Comment by ghost** [comment]
@Lazarus404  i'm trying with secure config , and i get the next errors.

<img width="1280" alt="screen shot 2015-09-14 at 3 31 43 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858211/d06bb19e-5af5-11e5-999c-85e945b602e9.png">

<img width="1280" alt="screen shot 2015-09-14 at 3 31 56 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858208/cac1240e-5af5-11e5-9ddc-1694a58688fb.png">

**Comment by Lazarus404** [comment]
Okay, so, these are suggesting the values you're using in your requests are wrong. Can you please post minus your shared secret?

**Comment by ghost** [comment]
@Lazarus404   ok, now i passed my  credentials  in the right way in secure mode , i think.

<img width="557" alt="screen shot 2015-09-14 at 3 40 40 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858467/3343c698-5af7-11e5-8a92-57f712d32031.png">

But i  have the same problem that i mentioned at the start, the request keep pending.

<img width="1280" alt="screen shot 2015-09-14 at 3 42 51 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858483/51d6ab48-5af7-11e5-9c98-3d42712da485.png">

<img width="1279" alt="screen shot 2015-09-14 at 3 42 58 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858484/51da62f6-5af7-11e5-8a11-492de16f4cfe.png">

**Comment by ghost** [comment]
@Lazarus404  ok, my error, now in secure mode it's working, my browser was caching some files, thanks so this config finally work just fine.

<img width="557" alt="screen shot 2015-09-14 at 3 40 40 pm" src="https://cloud.githubusercontent.com/assets/3533121/9858572/dac7e5f2-5af7-11e5-8c46-49199a553441.png">

Thanks.

**Comment by Lazarus404** [comment]
Thanks. I'll let you know what i find
