### ISSUE TITLE
BUG setting iceServers array when requested to xirsys API

### ISSUE THREAD

**Issue by eskalera** [xirdev/xsdk#4]
After a long time searching why my demo was not working with peers in different networks I found out that if I wrote `webrtc.ref.webrtc.config.peerConnectionConfig` in the console the iceServers array was empty. I thought it was due to the signalling server overriding my iceServer url but I ended up finding that there is a bug in lines [76](https://github.com/xirdev/xsdk/blob/master/lib/xirsys.simplewebrtc.js#L76) and [91](https://github.com/xirdev/xsdk/blob/master/lib/xirsys.simplewebrtc.js#L91).

`$data` must be changed to `$idata` in both lines of code.

**Comment by jerrychabolla** [comment]
Sweet, thanks for the find eskalera.  Updated.

**Comment by richardblakely** [comment]
We would also love to send you some Xirsys gifts for helping us out, we'll email you to get your delivery address. Thanks again!!
