### ISSUE TITLE
Incorrect argument to the connect() callback

### ISSUE THREAD

**Issue by blq** [xirdev/xsdk#6]
In xirsys.simplewebrtc.js connect() method.
I would say the line `$resp.apply(self, self.ref);` should instead be `$resp.apply(self, [self.ref]);` (or .call). otherwise the callback $resp won't correctly receive the SimpleWebRTC object.

Ref: https://github.com/xirdev/xsdk/blob/master/lib/xirsys.simplewebrtc.js#L62

**Comment by Lazarus404** [comment]
Thanks for finding.  Committed and pushed.

**Comment by blq** [comment]
Thanks for the fix!
But.. I think you accidentally merged more than the #6 fix?
You now point baseurl to local.com instead of xirsys, use "richie" in the example etc.
